version: "3.7"

services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: "postgres_db"
    env_file:
      - docker.env

  mongo:
    image: mongo
    restart: always
    container_name: "mongo_db"
    env_file:
      - docker.env

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    env_file:
      - docker.env
    depends_on:
      - mongo

  backend:
    image: anime-watch-backend
    build: ./backend/src
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    depends_on:
      - postgres
      - mongo

  frontend:
    image: anime-watch-frontend
    build: ./frontend/src
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - docker.env


