@startuml class

package pydantic {
    class BaseModel {
        __init__(...)
    }
}

package models {
    package schemes {
        package schemes.schemes {
            class Model {
                int id
            }

            BaseModel <|-- Model
        }

        package schemes.auth {
            class User {

            }

            Model <|-- User
        }

        package anime {
            class AnimeElement {
                Date publication_date
                Date previewed_date
                AnimeStatus anime_status
            }

            class Series {
                + int n
                + String name
                + SeasonOfAnime season
            }

            class SeasonOfAnime {
                + int n
                + Anime anime
                + Season season
            }

            class Anime {
                + User publisher
                + String originalName
                + String englishName
                + String russianName
                + String description
                + Stirng durationOfSeries
                + String ageRestriction
                
                + SeasonOfAnime[] getSeasons()
                + Series[] getSerieses()
            }

            class AnimeCategory {
                + String name
                + String description
            }

            class AnimeTag {
                + String name
                + String description
            }

            class Genre {
                + String name
                + String description
            }

            class Studio {
                + String name
                + String description
            }

            class Season {
                + int year
                + int timeOfYear
            }

            enum AnimeStatus {
                "Previewed",
                "Realesed"
                "Ongoing"
                "Leaved"
            }

            Model <|-- AnimeElement
            Model <|-- AnimeCategory
            Model <|-- AnimeTag
            Model <|-- Genre
            Model <|-- Studio
            Model <|-- Season

            AnimeElement <|-- Series
            AnimeElement <|-- SeasonOfAnime
            AnimeElement <|-- Anime

            AnimeElement - AnimeStatus

            SeasonOfAnime *-- Series
            Anime *-- SeasonOfAnime
        }
    }
}







class Comment {
    - User sender
    - String body
    - Date publishDate
    - CommentStatus status
    - IAnime parent

    + Comment Comment(parent, sender, body)
    + Comment Comment(parent, sender, body, status)

}

enum CommentStatus {
    "OnChecking"
    "Published"
    "Hidden"
}

@enduml