@startuml usecase

actor Viewer
actor User

(Get list of anime) as animeList

Viewer --> (Login)
Viewer --> (Regisration)
Viewer -left-> animeList
(Login) <.- (Username, password) : includes
(Regisration) <.- (Username, password) : includes

(Check profile) as profile
User -> profile
profile <. (Change username or/and password)

User --> animeList

animeList <.- (Search anime) : extends
(Search anime) <.- (Genres, tags, type, status) : extends
(Search anime) <.- (Open anime) : extends

animeList <.- (Open anime) : extends
(Open anime) <.- (Show description) : extends
(Open anime) <.- (Open series) : extends
(Open anime) <.- (Return to anime list) : extends
(Open anime) <.- (Leave commen logined only) : extends
(Open anime) <.- (Show comments) : extends
(Show comments) <.- (Go to profile) : extends


@enduml